import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { UserProvider } from "@/context/userContext";
import { GastosProvider } from "@/context/gastosContext";
import { IngresosProvider } from "@/context/incomeContext";
import Footer from "@/components/Footer";
import { GoogleOAuthProvider } from "@react-oauth/google";

const montserrat = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <UserProvider>
          <GoogleOAuthProvider
            clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string}
          >
            <GastosProvider>
            <IngresosProvider>
              {children}
            </IngresosProvider>
            </GastosProvider>
          </GoogleOAuthProvider>
        </UserProvider>
        <Footer />
      </body>
    </html>
  );
}
