import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { UserProvider } from "@/context/userContext";
import { GastosProvider } from "@/context/gastosContext";
const montserrat = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <UserProvider>
          <GastosProvider>{children}</GastosProvider>
        </UserProvider>
      </body>
    </html>
  );
}
